<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing pages
        \DB::table('pages')->truncate();

        $pages = [
            // Main Pages
            [
                'slug' => 'features',
                'title' => 'Features',
                'title_ar' => 'الميزات',
                'content' => 'Discover all the powerful features of our social media management platform.\n\nKey Features:\n- Multi-platform posting (Facebook, Twitter, Instagram, LinkedIn)\n- Advanced analytics and reporting\n- AI-powered content generation\n- Team collaboration tools\n- Scheduled posting\n- Content calendar\n- Hashtag suggestions\n- Performance tracking',
                'content_ar' => 'اكتشف جميع الميزات القوية لمنصة إدارة وسائل التواصل الاجتماعي الخاصة بنا.\n\nالميزات الرئيسية:\n- النشر على منصات متعددة (Facebook، Twitter، Instagram، LinkedIn)\n- التحليلات المتقدمة وإعداد التقارير\n- إنشاء المحتوى بمساعدة الذكاء الاصطناعي\n- أدوات التعاون الجماعي\n- النشر المجدول\n- تقويم المحتوى\n- اقتراحات الوسوم\n- تتبع الأداء',
                'meta_description' => 'Explore the powerful features of our social media management platform.',
                'meta_description_ar' => 'استكشف الميزات القوية لمنصة إدارة وسائل التواصل الاجتماعي الخاصة بنا.',
                'meta_keywords' => 'features, tools, capabilities, social media, management',
                'status' => 'published',
                'section' => 'main',
                'icon' => 'fas fa-star',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'pricing',
                'title' => 'Pricing Plans',
                'title_ar' => 'خطط التسعير',
                'content' => 'Choose the perfect plan for your needs. We offer flexible pricing options for individuals and businesses.\n\nPlans:\n- Free Plan: Perfect for getting started - $0/month\n- Pro Plan: For growing businesses - $29/month\n- Enterprise Plan: For large organizations - Custom pricing\n\nAll plans include 24/7 support and regular updates.',
                'content_ar' => 'اختر الخطة المثالية لاحتياجاتك. نحن نقدم خيارات تسعير مرنة للأفراد والشركات.\n\nالخطط:\n- الخطة المجانية: مثالية للبدء - 0 دولار / شهر\n- الخطة الاحترافية: للشركات المتنامية - 29 دولار / شهر\n- الخطة المؤسسية: للمؤسسات الكبيرة - تسعير مخصص\n\nتتضمن جميع الخطط دعم على مدار الساعة وتحديثات منتظمة.',
                'meta_description' => 'View our pricing plans and choose the perfect package for your social media management needs.',
                'meta_description_ar' => 'اطلع على خطط الأسعار لدينا واختر الحزمة المثالية لاحتياجات إدارة وسائل التواصل الاجتماعي الخاصة بك.',
                'meta_keywords' => 'pricing, plans, subscription, cost, free, pro, enterprise',
                'status' => 'published',
                'section' => 'main',
                'icon' => 'fas fa-tag',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'api',
                'title' => 'API Documentation',
                'title_ar' => 'واجهة برمجية',
                'content' => 'Integrate our platform with your applications using our powerful API.\n\nGetting Started:\n1. Create an API key in your account settings\n2. Review the API documentation\n3. Make your first API call\n\nView our complete API documentation for all available endpoints and features.',
                'content_ar' => 'دمج منصتنا مع تطبيقاتك باستخدام API القوي لدينا.\n\nالبدء:\n1. إنشاء مفتاح API في إعدادات حسابك\n2. مراجعة توثيق API\n3. إجراء أول استدعاء API لك\n\nاطلع على توثيق API الكامل لدينا لجميع نقاط النهاية والميزات المتاحة.',
                'meta_description' => 'Learn how to integrate with our platform using our comprehensive API documentation.',
                'meta_description_ar' => 'تعلم كيفية التكامل مع منصتنا باستخدام توثيق API الشامل لدينا.',
                'meta_keywords' => 'api, documentation, integration, developers, endpoints',
                'status' => 'published',
                'section' => 'main',
                'icon' => 'fas fa-code',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Company Pages
            [
                'slug' => 'about',
                'title' => 'About Us',
                'title_ar' => 'من نحن',
                'content' => 'Welcome to our social media management platform. We help businesses and individuals manage their social media presence across multiple platforms efficiently.\n\nOur mission is to simplify social media management and help you grow your online presence.',
                'content_ar' => 'مرحبًا بك في منصة إدارة وسائل التواصل الاجتماعي الخاصة بنا. نحن نساعد الشركات والأفراد على إدارة وجودهم على وسائل التواصل الاجتماعي عبر منصات متعددة بكفاءة.\n\nمهمتنا هي تبسيط إدارة وسائل التواصل الاجتماعي ومساعدتك على تنمية تواجدك عبر الإنترنت.',
                'meta_description' => 'Learn more about our social media management platform and how we help businesses grow online.',
                'meta_description_ar' => 'تعرف على المزيد حول منصة إدارة وسائل التواصل الاجتماعي الخاصة بنا وكيف نساعد الشركات على النمو عبر الإنترنت.',
                'meta_keywords' => 'about, social media, management, platform',
                'status' => 'published',
                'section' => 'company',
                'icon' => 'fas fa-users',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'blog',
                'title' => 'Blog',
                'title_ar' => 'المدونة',
                'content' => 'Stay updated with the latest tips, tricks, and news about social media marketing.\n\nRecent Posts:\n- 10 Tips for Better Social Media Engagement\n- How to Create Viral Content\n- Social Media Trends in 2025\n- Mastering Instagram Marketing',
                'content_ar' => 'ابق على اطلاع بأحدث النصائح والحيل والأخبار حول التسويق عبر وسائل التواصل الاجتماعي.\n\nالمنشورات الأخيرة:\n- 10 نصائح لتفاعل أفضل عبر وسائل التواصل الاجتماعي\n- كيفية إنشاء محتوى فيروسي\n- اتجاهات وسائل التواصل الاجتماعي في 2025\n- إتقان التسويق على Instagram',
                'meta_description' => 'Read our blog for social media tips, marketing strategies, and industry insights.',
                'meta_description_ar' => 'اقرأ مدونتنا للحصول على نصائح وسائل التواصل الاجتماعي واستراتيجيات التسويق ورؤى الصناعة.',
                'meta_keywords' => 'blog, articles, tips, social media, marketing',
                'status' => 'published',
                'section' => 'company',
                'icon' => 'fas fa-blog',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'careers',
                'title' => 'Careers',
                'title_ar' => 'الوظائف',
                'content' => 'We\'re always looking for talented individuals to join our growing team.\n\nWhy Work With Us?\n- Competitive salary\n- Remote work options\n- Health benefits\n- Professional development\n- Great team culture\n\nOpen Positions: Check back soon for available positions or send your resume to careers@socialmediamanager.com',
                'content_ar' => 'نحن نبحث دائمًا عن أفراد موهوبين للانضمام إلى فريقنا المتنامي.\n\nلماذا تعمل معنا؟\n- راتب تنافسي\n- خيارات العمل عن بُعد\n- مزايا صحية\n- تطوير مهني\n- ثقافة فريق رائعة\n\nالوظائف المتاحة: تحقق مرة أخرى قريبًا من الوظائف المتاحة أو أرسل سيرتك الذاتية إلى careers@socialmediamanager.com',
                'meta_description' => 'Join our team and help build the future of social media management.',
                'meta_description_ar' => 'انضم إلى فريقنا وساعد في بناء مستقبل إدارة وسائل التواصل الاجتماعي.',
                'meta_keywords' => 'careers, jobs, employment, hiring, team',
                'status' => 'published',
                'section' => 'company',
                'icon' => 'fas fa-briefcase',
                'show_in_header' => 0,
                'show_in_footer' => 1,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Resources Pages
            [
                'slug' => 'help',
                'title' => 'Help Center',
                'title_ar' => 'مركز المساعدة',
                'content' => 'Find answers to common questions and learn how to use our platform effectively.\n\nGetting Started:\n- How to create an account\n- Connecting your social media accounts\n- Creating your first post\n\nNeed More Help? Contact our support team at support@socialmediamanager.com',
                'content_ar' => 'اعثر على إجابات للأسئلة الشائعة وتعلم كيفية استخدام منصتنا بفعالية.\n\nالبدء:\n- كيفية إنشاء حساب\n- ربط حسابات وسائل التواصل الاجتماعي الخاصة بك\n- إنشاء منشورك الأول\n\nهل تحتاج إلى مزيد من المساعدة؟ اتصل بفريق الدعم لدينا على support@socialmediamanager.com',
                'meta_description' => 'Get help and find answers to your questions in our comprehensive help center.',
                'meta_description_ar' => 'احصل على المساعدة واعثر على إجابات لأسئلتك في مركز المساعدة الشامل لدينا.',
                'meta_keywords' => 'help, support, faq, questions, guide',
                'status' => 'published',
                'section' => 'resources',
                'icon' => 'fas fa-question-circle',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'community',
                'title' => 'Community',
                'title_ar' => 'المجتمع',
                'content' => 'Connect with other social media professionals and learn from each other.\n\nCommunity Features:\n- Discussion forums\n- Member meetups\n- Webinars and workshops\n- Resource sharing\n- Networking opportunities\n\nSign up today and become part of our growing community!',
                'content_ar' => 'تواصل مع محترفي وسائل التواصل الاجتماعي الآخرين وتعلم من بعضكم البعض.\n\nميزات المجتمع:\n- منتديات النقاش\n- لقاءات الأعضاء\n- ندوات عبر الإنترنت وورش عمل\n- مشاركة الموارد\n- فرص التواصل\n\nسجل اليوم وكن جزءًا من مجتمعنا المتنامي!',
                'meta_description' => 'Join our community of social media professionals and grow your network.',
                'meta_description_ar' => 'انضم إلى مجتمعنا من محترفي وسائل التواصل الاجتماعي ووسّع شبكتك.',
                'meta_keywords' => 'community, forum, networking, members, professionals',
                'status' => 'published',
                'section' => 'resources',
                'icon' => 'fas fa-users-cog',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'contact',
                'title' => 'Contact Us',
                'title_ar' => 'اتصل بنا',
                'content' => 'We\'d love to hear from you! Get in touch with our team for any questions or support.\n\nContact Information:\n- Email: support@socialmediamanager.com\n- Phone: +1 (555) 123-4567\n- Address: 123 Social Media St, Digital City, DC 12345',
                'content_ar' => 'نود أن نسمع منك! تواصل مع فريقنا لأي أسئلة أو دعم.\n\nمعلومات الاتصال:\n- البريد الإلكتروني: support@socialmediamanager.com\n- الهاتف: +1 (555) 123-4567\n- العنوان: 123 شارع وسائل التواصل، المدينة الرقمية، DC 12345',
                'meta_description' => 'Get in touch with our support team. Contact us for any questions about our platform.',
                'meta_description_ar' => 'تواصل مع فريق الدعم لدينا. اتصل بنا لأي أسئلة حول منصتنا.',
                'meta_keywords' => 'contact, support, help, email, phone',
                'status' => 'published',
                'section' => 'resources',
                'icon' => 'fas fa-envelope',
                'show_in_header' => 1,
                'show_in_footer' => 1,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Legal Pages
            [
                'slug' => 'privacy',
                'title' => 'Privacy Policy',
                'title_ar' => 'الخصوصية',
                'content' => 'Last updated: ' . date('F d, Y') . '\n\nInformation We Collect:\nWe collect information you provide directly to us when you create an account, use our services, or contact us.\n\nHow We Use Your Information:\nWe use the information we collect to provide, maintain, and improve our services.\n\nData Security:\nWe take reasonable measures to protect your information from unauthorized access.',
                'content_ar' => 'آخر تحديث: ' . date('F d, Y') . '\n\nالمعلومات التي نجمعها:\nنقوم بجمع المعلومات التي تقدمها لنا مباشرة عند إنشاء حساب أو استخدام خدماتنا أو الاتصال بنا.\n\nكيف نستخدم معلوماتك:\nنستخدم المعلومات التي نجمعها لتوفير خدماتنا وصيانتها وتحسينها.\n\nأمن البيانات:\nنتخذ تدابير معقولة لحماية معلوماتك من الوصول غير المصرح به.',
                'meta_description' => 'Read our privacy policy to understand how we collect, use, and protect your personal information.',
                'meta_description_ar' => 'اقرأ سياسة الخصوصية الخاصة بنا لفهم كيفية جمع واستخدام وحماية معلوماتك الشخصية.',
                'meta_keywords' => 'privacy, policy, data, security, protection',
                'status' => 'published',
                'section' => 'legal',
                'icon' => 'fas fa-shield-alt',
                'show_in_header' => 0,
                'show_in_footer' => 1,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'terms',
                'title' => 'Terms of Service',
                'title_ar' => 'الشروط',
                'content' => 'Last updated: ' . date('F d, Y') . '\n\nAcceptance of Terms:\nBy accessing and using our service, you accept and agree to be bound by these terms.\n\nUse License:\nWe grant you a limited, non-exclusive, non-transferable license to use our platform.\n\nUser Responsibilities:\nYou are responsible for maintaining the confidentiality of your account credentials.',
                'content_ar' => 'آخر تحديث: ' . date('F d, Y') . '\n\nقبول الشروط:\nمن خلال الوصول إلى خدمتنا واستخدامها، فإنك تقبل وتوافق على الالتزام بهذه الشروط.\n\nترخيص الاستخدام:\nنمنحك ترخيصًا محدودًا وغير حصري وغير قابل للتحويل لاستخدام منصتنا.\n\nمسؤوليات المستخدم:\nأنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك.',
                'meta_description' => 'Read our terms of service to understand the rules and regulations for using our platform.',
                'meta_description_ar' => 'اقرأ شروط الخدمة الخاصة بنا لفهم القواعد واللوائح الخاصة باستخدام منصتنا.',
                'meta_keywords' => 'terms, service, agreement, legal, conditions',
                'status' => 'published',
                'section' => 'legal',
                'icon' => 'fas fa-file-contract',
                'show_in_header' => 0,
                'show_in_footer' => 1,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'security',
                'title' => 'Security',
                'title_ar' => 'الأمان',
                'content' => 'Your data security is our top priority. Learn about our security measures.\n\nSecurity Features:\n- 256-bit SSL encryption\n- Two-factor authentication\n- Regular security audits\n- Data backup and recovery\n- GDPR compliant\n- SOC 2 certified\n\nReport Security Issues: If you discover a security vulnerability, please email security@socialmediamanager.com',
                'content_ar' => 'أمان بياناتك هو أولويتنا القصوى. تعرف على إجراءات الأمان لدينا.\n\nميزات الأمان:\n- تشفير SSL 256 بت\n- المصادقة الثنائية\n- عمليات تدقيق أمنية منتظمة\n- النسخ الاحتياطي للبيانات والاسترداد\n- متوافق مع GDPR\n- معتمد SOC 2\n\nالإبلاغ عن مشكلات الأمان: إذا اكتشفت ثغرة أمنية، يرجى إرسال بريد إلكتروني إلى security@socialmediamanager.com',
                'meta_description' => 'Learn about our security measures and commitment to protecting your data.',
                'meta_description_ar' => 'تعرف على إجراءات الأمان لدينا والتزامنا بحماية بياناتك.',
                'meta_keywords' => 'security, privacy, encryption, compliance, protection',
                'status' => 'published',
                'section' => 'legal',
                'icon' => 'fas fa-lock',
                'show_in_header' => 0,
                'show_in_footer' => 1,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($pages as $page) {
            \DB::table('pages')->insert($page);
        }
    }
}
